### ISSUE TITLE
How to connect MongoDB with replica set?

### ISSUE THREAD

**Issue by hustshawn** [TykTechnologies/tyk#1798]
**Do you want to request a *feature* or report a *bug*?**
no
**What is the current behavior?**
currently, I can only specify a mongodb connection string like: `mongodb://host1:27107`
**What is the expected behavior?**
If I have a mongodb cluster( replicaset name is rs0), eg. host1:27017, host2:27017, host3:27017, 
I may wish I have the connection string as:
`mongodb://host1:27017,host2:27017,host3:27017/?replicaSet=rs0`, 
so that tyk will automatically pickup the primary node to write data in .
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
latest

**Comment by asoorm** [comment]
Hi - You should be able to use the standard MongoDB connection string format:

```
mongodb://[username:password@]host1[:port1][,host2[:port2],...[,hostN[:portN]]][/[database][?options]]
```

https://docs.mongodb.com/manual/reference/connection-string/#standard-connection-string-format

Does the above not work for you?

**Comment by hustshawn** [comment]
@asoorm It works. Thank you.

**Comment by hustshawn** [comment]
Hi @asoorm , a further problem is, I set the mongoDB connection in my dashboard config file, and the dashboard is running file, can load and write configs into the Mongo. However, the tyk_gateway is not able to load the api definitions from the the MongoDB. As your [Doc](https://tyk.io/docs/configure/tyk-gateway-configuration-options/#a-name-use-db-app-options-connection-string-a-use-db-app-options-connection-string) indicates, the tyk_gateway will load configs via tyk_dashboard. But actually the gateway itself does not work.
in `tyk.conf`
```
...
    "policies": {
        "policy_source": "service",
        "policy_connection_string": "http://tyk_dashboard:3000",
        "policy_record_name": "tyk_policies"
    },
  ...
```

in `tyk_analytics.conf`,

```
...
    "mongo_url": "mongodb://mongohost1:27017,mongohost2:mongohost3:27019/tyk_analytics",
...
```
Where I got below logs in tyk_gateway
```
Attaching to ifundtyk_tyk_gateway_1
tyk_gateway_1    | sed: cannot rename /opt/tyk-gateway/sedtY3Cuu: Device or resource busy
tyk_gateway_1    | sed: cannot rename /opt/tyk-gateway/sedFNNUFx: Device or resource busy
```
Based on my previous experience, this kind of  log normally occurs whenever it cannot get configs from mongo, that is why I suspect the tyk_gateway is not able to load configs right.

Any ideas about this?

**Comment by excieve** [comment]
Hi @hustshawn, this message looks like an issue with docker container. Could you please share which docker image are you using and how are you starting the container?

**Comment by hustshawn** [comment]
Hi @excieve , I am using docker-compose to bring up all components. 
Here is the `docker-compose.yml`
```
version: '2'

services:
    tyk_dashboard:
        image: tykio/tyk-dashboard:v1.6.2
        restart: always
        ports:
            - "3000:3000"
            - "5000:5000"
        volumes:
            - ./tyk_analytics.conf:/opt/tyk-dashboard/tyk_analytics.conf
        extra_hosts:
            - "redis:10.8.3.228"
        networks:
            - gateway
    tyk_pump:
        image: tykio/tyk-pump-docker-pub:latest
        restart: always
        networks:
            - gateway
        extra_hosts:
            - "redis:10.8.3.228"
        volumes:
            - ./pump.conf:/opt/tyk-pump/pump.conf
    tyk_gateway:
        image: tykio/tyk-gateway:v2.6.2
        restart: always
        expose:
            - "8080"
        ports:
            - "8080:8080"
        extra_hosts:
            - "redis:10.8.3.228"
        volumes:
            - ./tyk.conf:/opt/tyk-gateway/tyk.conf
            - ./middleware:/opt/tyk-gateway/middleware
        networks:
            - gateway
networks:
    gateway:

```
