### ISSUE TITLE
How environment variables for Redis be applied?

### ISSUE THREAD

**Issue by hustshawn** [TykTechnologies/tyk#1813]
**Do you want to request a *feature* or report a *bug*?**
bug?
**What is the current behavior?**
As indicate in https://tyk.io/docs/configure/gateway-env-variables/ , when I set the environment variables like below, it should replace the configuration from the `tyk.conf`. However, I do not see the config be recognized by tyk-gateawy
```
TYK_GW_STORAGE_TYPE=redis
TYK_GW_STORAGE_HOST=10.8.3.228
TYK_GW_STORAGE_PORT=6379
```
The error log is as below

```
...
tyk_gateway_1    | sed: cannot rename /opt/tyk-gateway/sedMT6xfQ: Device or resource busy

...
tyk_dashboard_1  | time="Jul 11 07:42:01" level=info msg="Creating new Redis connection pool" 
tyk_dashboard_1  | time="Jul 11 07:42:01" level=info msg="Creating new Redis connection pool" 
tyk_dashboard_1  | time="Jul 11 07:42:01" level=info msg="Creating new Redis connection pool" 
tyk_dashboard_1  | time="Jul 11 07:42:01" level=info msg="Creating new Redis connection pool" 
tyk_dashboard_1  | time="Jul 11 07:42:01" level=info msg="Adding available nodes..." 
tyk_dashboard_1  | time="Jul 11 07:42:01" level=error msg="Failed to add NodeID to register: dial tcp: lookup redis on 127.0.0.11:53: no such host" 
tyk_dashboard_1  | time="Jul 11 07:42:01" level=info msg="Tyk Analytics Dashboard v1.5.4" 
tyk_dashboard_1  | time="Jul 11 07:42:01" level=info msg="Copyright Martin Buhr 2016" 
tyk_dashboard_1  | time="Jul 11 07:42:01" level=info msg="https://www.tyk.io" 
tyk_dashboard_1  | time="Jul 11 07:42:01" level=info msg="Listening on port: 3000" 
tyk_dashboard_1  | time="Jul 11 07:42:01" level=info msg="Registering nodes..." 
tyk_dashboard_1  | time="Jul 11 07:42:01" level=info msg="Creating new Redis connection pool" 
tyk_dashboard_1  | time="Jul 11 07:42:01" level=info msg="Socket server started" 
tyk_dashboard_1  | time="Jul 11 07:42:01" level=info msg="--> Standard listener (http) for UI notifications" addr=":5000" 
tyk_dashboard_1  | time="Jul 11 07:42:01" level=info msg="Adding available nodes..." 
tyk_dashboard_1  | time="Jul 11 07:42:01" level=error msg="Failed to add NodeID to register: dial tcp: lookup redis on 127.0.0.11:53: no such host" 
tyk_dashboard_1  | time="Jul 11 07:42:01" level=info msg="--> Standard listener (http) for dashboard and API" 
tyk_dashboard_1  | time="Jul 11 07:42:01" level=info msg="Starting zeroconf heartbeat" 
tyk_dashboard_1  | time="Jul 11 07:42:01" level=info msg="Starting notification handler for gateway cluster" 
tyk_dashboard_1  | time="Jul 11 07:42:01" level=info msg="Loading routes..." 
tyk_dashboard_1  | time="Jul 11 07:42:01" level=error msg="Redis disconnected or error received, attempting to reconnect: dial tcp: lookup redis on 127.0.0.11:53: no such host" 
tyk_dashboard_1  | time="Jul 11 07:42:01" level=error msg="Connection to Redis failed, reconnect in 10s" err="dial tcp: lookup redis on 127.0.0.11:53: no such host" 
tyk_dashboard_1  | time="Jul 11 07:42:02" level=error msg="Could not send notification" 
tyk_dashboard_1  | time="Jul 11 07:42:02" level=error msg="dial tcp: lookup redis on 127.0.0.11:53: no such host" 
tyk_dashboard_1  | time="Jul 11 07:42:02" level=error msg="Redis disconnected or error received, attempting to reconnect: dial tcp: lookup redis on 127.0.0.11:53: no such host" 
tyk_dashboard_1  | time="Jul 11 07:42:04" level=error msg="Could not send notification" 
tyk_dashboard_1  | time="Jul 11 07:42:04" level=error msg="dial tcp: lookup redis on 127.0.0.11:53: no such host" 
tyk_dashboard_1  | time="Jul 11 07:42:06" level=error msg="Could not send notification" 
tyk_dashboard_1  | time="Jul 11 07:42:06" level=error msg="dial tcp: lookup redis on 127.0.0.11:53: no such host" 
tyk_dashboard_1  | time="Jul 11 07:42:08" level=error msg="Could not send notification" 
tyk_dashboard_1  | time="Jul 11 07:42:08" level=error msg="dial tcp: lookup redis on 127.0.0.11:53: no such host" 
tyk_dashboard_1  | time="Jul 11 07:42:10" level=error msg="Could not send notification" 
tyk_dashboard_1  | time="Jul 11 07:42:10" level=error msg="dial tcp: lookup redis on 127.0.0.11:53: no such host" 
tyk_dashboard_1  | time="Jul 11 07:42:11" level=warning msg=Reconnecting 
tyk_dashboard_1  | time="Jul 11 07:42:11" level=info msg="Creating new Redis connection pool" 
tyk_dashboard_1  | time="Jul 11 07:42:12" level=error msg="Redis disconnected or error received, attempting to reconnect: dial tcp: lookup redis on 127.0.0.11:53: no such host" 
tyk_dashboard_1  | time="Jul 11 07:42:12" level=error msg="Redis disconnected or error received, attempting to reconnect: dial tcp: lookup redis on 127.0.0.11:53: no such host" 
tyk_dashboard_1  | time="Jul 11 07:42:12" level=error msg="Connection to Redis failed, reconnect in 10s" err="dial tcp: lookup redis on 127.0.0.11:53: no such host" 

```

And I am sure the redis itself working fine.

**What is the expected behavior?**
Tyk is able to pick up redis.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
latest docker build

**Comment by asoorm** [comment]
Quick question, are you using `https://github.com/TykTechnologies/tyk-pro-docker-demo`? Your log output looks like a docker-compose. It would be useful to see this (with sensitive info redacted) to assist debugging the issue.

Separately - it looks like there is an issue with the gateway too `tyk_gateway_1    | sed: cannot rename /opt/tyk-gateway/sedMT6xfQ: Device or resource busy` and this could be because `sed` doesn't play well with mounted volumes.

**Comment by asoorm** [comment]
Actually - the logs you have shown us are dashboard logs. but env vars you have set are for the gateway.

```
redis_port | TYK_DB_REDISPORT
redis_host | TYK_DB_REDISHOST
redis_password | TYK_DB_REDISPASSWORD
```

https://tyk.io/docs/configure/dashboard-env-variables/

Try setting these also so that the dashboard will also be able to communicate with the same redis as the gateway.

**Comment by hustshawn** [comment]
Hi @asoorm , thanks for your prompt suggestion.

1. For the `tyk_gateway_1 | sed: cannot rename /opt/tyk-gateway/sedMT6xfQ` sed issue, I think it's already in your fix schedule, as mentioned in this [issue](https://github.com/TykTechnologies/tyk-gateway-docker/pull/15)
2. Yes. I am using `docker-compose`, please see the `docker-compose.yml` here
```
version: '2'

services:
    tyk_dashboard:
        image: tykio/tyk-dashboard:latest
        restart: always
        ports:
            - "3000:3000"
            - "5000:5000"
        volumes:
            - ./tyk_analytics.conf:/opt/tyk-dashboard/tyk_analytics.conf
        env_file: .env
        networks:
            - gateway
    tyk_pump:
        image: tykio/tyk-pump-docker-pub:latest
        restart: always
        networks:
            - gateway
        env_file: .env
        volumes:
            - ./pump.conf:/opt/tyk-pump/pump.conf
    tyk_gateway:
        # image: tykio/tyk-gateway:v2.3.8
        image: tykio/tyk-gateway:latest
        restart: always
        expose:
            - "8080"
        ports:
            - "8080:8080"
        env_file: .env
        volumes:
            - ./tyk.conf:/opt/tyk-gateway/tyk.conf
            - ./middleware:/opt/tyk-gateway/middleware
        networks:
            - gateway

networks:
    gateway:
```
3. Before using environment variables `TYK_GW_`,  I  used the settings in  `tyk.conf` is
```
    "storage": {
        "type": "redis",
        "host": "redis",
        "port": 6379,
        "username": "",
        "password": "",
        "database": 0,
        "optimisation_max_idle": 100
    },
```
and in `tyk_analytics.conf` is 
```
    "redis_port": 6379,
    "redis_host": "redis",
    "redis_password": "",
    "enable_cluster": false,
```
where in the `docker-compose.yml` , I added a `extra_hosts` field, to enable the `redis` be resolved 
```  extra_hosts:
            - "redis:10.8.3.228"
```
and it works fine.
