### ISSUE TITLE
support yaml format API definitions for tyk gateway running headless

### ISSUE THREAD

**Issue by asoorm** [TykTechnologies/tyk#2757]
**Describe the solution you'd like**

I would like to be able to define my API definitions in YAML format

**Additional context**

Most Basic API definition with Tyk CE keyless API

```json
{
  "name": "httpbin",
  "api_id": "httpbin",
  "use_keyless": true,
  "active": true,
  "version_data": {
    "not_versioned": true,
    "versions": {
      "Default": {
        "name": "Default"
      }
    }
  },
  "proxy": {
    "listen_path": "/httpbin",
    "target_url": "http://httpbin.org/",
    "strip_listen_path": true
  }
}
```

Proposal in YAML format

```yaml
name: httpbin
api_id: httpbin
use_keyless: true
active: true
version_data:
  not_versioned: true
  versions:
    Default:
      name: Default
proxy:
  listen_path: "/httpbin"
  target_url: http://httpbin.org/
  strip_listen_path: true
```

Aside from better readability, we can also benefit from being able to add comments

```yaml
name: httpbin
# this is the api id that you will use to query the api definition
api_id: httpbin
# this disables authentication for your API
use_keyless: true
# active tells tyk gateway whether to enable or disable a given api
active: true
...
```
