### ISSUE TITLE
Service doesn't detach from invoking terminal and receives SIGQUIT if controlling terminal goes away (Ansible)

### ISSUE THREAD

**Issue by csbogdan** [TykTechnologies/tyk#931]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
Can not use Ansible with Amazon Linux for tyk gateway or dashboard.

If using Ansible shell module to execute `/etc/init.d/tyk-gateway` start or `service tyk-gateway start`, in some scenarios service process doesn't disassociate from the controlling terminal, receiving a SIGQUIT when terminal goes away. This results in service starting and terminating very quickly.

if using Ansible service module, receiving error "unknown job: tyk-gateway"

Final result is there is no wy to start tyk gateway or dashboard while using Ansible on Amazon Linux.
 
**What is the expected behavior?**
Service would start and detach properly
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Using Amazon Linux AIM and Ansible 2.2.0.0 and 2.3.1.0, and service module

task for starting tyk-gateway:
```
- hosts: dashboard
  become: yes
  become_method: sudo
  become_user: root
  tasks:
    - service:
        name: tyk-gateway
        state: started
```
Ansible result:
`start: Unknown job: tyk-gateway`

Using Amazon Linux AIM and Ansible 2.2.0.0 and 2.3.1.0, and shell module
task for starting tyk-gateway method 1:
```
- hosts: all
  become: yes
  become_method: sudo
  become_user: root
  tasks:
    - shell: "/etc/init.d/tyk-gateway start"
```
Ansible result:
` "stdout_lines": ["Starting tyk-gateway: [  OK  ]"`
Actual result:
Service starts and quits immediately. Log files are created, but empty.

task for starting tyk-gateway method 2:
```
- hosts: all
  become: yes
  become_method: sudo
  become_user: root
  tasks:
    - shell: "service tyk-gateway start"
```
Ansible result:
` "stdout_lines": ["Starting tyk-gateway: [  OK  ]"`
Actual result:
Service starts and quits immediately. Log files are created, but empty.

task for starting tyk-gateway method 3:
```
- hosts: all
  become: yes
  become_method: sudo
  become_user: root
  tasks:
    - shell: "/etc/init.d/tyk-gateway start && sleep 10"
```
Ansible result:
` "stdout_lines": ["Starting tyk-gateway: [  OK  ]"`
Actual result:
Service starts and quits after 10 seconds. Log files are created, after 10 seconds `SIGQUIT: quit` is present in log file.

Manual ssh on the target machine and issuing `service tyk-gateway` starts service correctly.

Workaround:
new service file that uses `daemon nohup $prog $args` to start the service, where `prog=/opt/tyk-gateway/tyk` and `args="--conf=/opt/tyk-gateway/tyk.conf"`

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
2.x
